import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import SidebarLeft from "@/components/SidebarLeft";
import Footer from "@/components/Footer";
import HeroContent from "@/components/MainPage/HeroContent";
import Navbar from "@/components/Navbar";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <section>
          <HeroContent data={data} />
        </section>
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "https://gorest.co.in/public/v2/posts?per_page=6"
  );
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
